### ISSUE TITLE
Channel epg disappeared

### ISSUE THREAD

**Issue by Shawkiiz** [bebawy6/bebawy6#2]
Hay bro ,,
I hope you are good 

I have problem, all mbc and rotana and some egyptian channels epg info disappeared, I hope to solve the problem

Thx,,

**Comment by bebawy6** [comment]
source is down searching for alternative

**Comment by Shawkiiz** [comment]
Is there an alternative that you recommend?

**Comment by Shawkiiz** [comment]
You can use 👇🏼
https://elcinema.com/tvguide/

**Comment by bebawy6** [comment]
I am looking for alternative sources because Elcinema is an unreliable source. Their program guide does not match the live stream and requires frequent adjustments. However, if I am unable to find another source, I will still use Elcinema as I did for your previous request, since they are the only source providing a guide for the MIX channel.
